# Generated by Django 5.1.7 on 2025-03-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='account',
        #     old_name='balance',
        #     new_name='available_balance',
        # ),
        migrations.AddField(
            model_name='account',
            name='pending_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
