# Generated by Django 5.1.7 on 2025-05-27 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={},
        ),
        migrations.RemoveField(
            model_name='refund',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='created',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refund',
            name='account_name',
            field=models.CharField(default='Frank Neba', max_length=255),
        ),
        migrations.AddField(
            model_name='refund',
            name='account_number',
            field=models.CharField(default='677482442', max_length=9),
        ),
        migrations.AddField(
            model_name='refund',
            name='evidense',
            field=models.FileField(default='hello.pdf', upload_to='refund/evidense/'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment_method',
            field=models.CharField(choices=[('mtnmomo', 'MTN Mobile Money'), ('orangemomo', 'Orange Mobile Money')], default='MTN', max_length=255),
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='refund',
            name='submited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
    ]
