# Generated by Django 5.1.7 on 2025-05-27 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_refund_options_remove_refund_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refund',
            unique_together={('user', 'order')},
        ),
    ]
