# Generated by Django 5.1.7 on 2025-03-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_image_subcategory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='IDCard',
            field=models.ImageField(null=True, upload_to='IDcards/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_image',
            field=models.ImageField(null=True, upload_to='shop_profiles/'),
        ),
    ]
