# Generated by Django 5.1.7 on 2025-06-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='name',
            field=models.CharField(default='neba', max_length=200),
        ),
    ]
