# Generated by Django 5.1.7 on 2025-03-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Location',
            new_name='location',
        ),
    ]
