# Generated by Django 5.1.7 on 2025-06-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_item_is_resale_item_original_item_order_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='secret_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='6ADT5C', max_length=10),
        ),
    ]
