# Generated by Django 5.1.7 on 2025-06-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_item_is_custom_item_secret_code_alter_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delivery',
            field=models.TextField(null=True),
        ),
    ]
