# Generated by Django 5.1.7 on 2025-03-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='677482442', max_length=9),
        ),
    ]
