# Generated by Django 5.1.7 on 2025-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='1111111111', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(default='0', max_length=9),
        ),
    ]
