# Generated by Django 5.1.7 on 2025-06-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_sold',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
