# Generated by Django 5.1.7 on 2025-03-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_category_name_alter_item_location'),
        ('shop', '0012_order_payment_status'),
    ]

    operations = [
    ]
