# Generated by Django 5.1.7 on 2025-03-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_merge_20250316_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw', to='shop.shop')),
            ],
        ),
    ]
