# Generated by Django 5.1.7 on 2025-03-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_order_payment_status_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='service',
            field=models.CharField(default='MTN', max_length=20),
        ),
    ]
