# Generated by Django 5.1.7 on 2025-04-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_withdrawal_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='amount_to_receive',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='charges',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
