# Generated by Django 5.1.7 on 2025-04-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_withdrawal_amount_to_receive_withdrawal_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='amount_to_receive',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
