# Generated by Django 5.1.7 on 2025-04-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_payment_status copy'),
        ('shop', '0018_alter_withdrawal_amount_to_receive'),
    ]

    operations = [
    ]
