# Generated by Django 5.1.7 on 2025-04-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_merge_20250428_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='amount_to_receive',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
