# Generated by Django 5.1.7 on 2025-04-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_withdrawal_amount_to_receive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='amount_to_receive',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
