# Generated by Django 5.1.7 on 2025-04-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_withdrawal_amount_to_receive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='amount_to_receive',
        ),
    ]
