# Generated by Django 5.1.7 on 2025-04-28 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_withdrawal_amount_to_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
