# Generated by Django 5.1.7 on 2025-04-28 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_image_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Rejected', 'REJECTED'), ('Paid', 'PAID')], max_length=20)),
                ('reason', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
