# Generated by Django 5.1.7 on 2025-04-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
