# Generated by Django 5.1.7 on 2025-04-30 16:18

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_refund_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='IDCard',
        ),
        migrations.AddField(
            model_name='shop',
            name='back_IDCard',
            field=models.ImageField(null=True, upload_to=shop.models.Id_card_directory),
        ),
        migrations.AddField(
            model_name='shop',
            name='front_IDCard',
            field=models.ImageField(null=True, upload_to=shop.models.Id_card_directory),
        ),
    ]
