# Generated by Django 5.1.7 on 2025-05-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_remove_shop_idcard_shop_back_idcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default='6ADT5C', max_length=6),
        ),
    ]
