# Generated by Django 5.1.7 on 2025-05-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to='shop_profiles/'),
        ),
    ]
