# Generated by Django 5.1.7 on 2025-03-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
