# Generated by Django 5.1.7 on 2025-03-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_location_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
    ]
