# Generated by Django 5.1.7 on 2025-04-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.PositiveIntegerField()),
                ('withdrawal', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
    ]
